=== safaelazrak/XML_project/EMR.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="Electronic_Medical_Records" type="EMRStype"/>
		<xs:complexType name="EMRStype">
			<xs:sequence>
			<xs:element name="Employee" type="Employeetype" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			</xs:complexType>
			<xs:complexType name="Employeetype">
			<xs:sequence>
			<xs:element name="personal_data" type="personal_datatype" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Claim_informations" type="claiminfotype" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Insurance_informations" type="insurancetype" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Medical_history" type="medicaltype" />
			</xs:sequence>
			</xs:complexType>
			<xs:complexType name="personal_datatype">
			<xs:sequence>
										<xs:element name="ID" type="xs:integer" minOccurs="0" maxOccurs="1"/>
										<xs:element name="firstname" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="lastname" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="date_of_birth" type="xs:date" minOccurs="0" maxOccurs="1"/>
										<xs:element name="current_age" type="xs:integer" minOccurs="0" maxOccurs="1"/>
										<xs:element name="weight_in_kg" type="xs:decimal" minOccurs="0" maxOccurs="1"/>
										<xs:element name="Gender" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="phone_number" type="xs:string" minOccurs="0" maxOccurs="2"/>
										<xs:element name="email_adress" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="city" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="address" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="zipcode" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="emergency_contact" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="phone_emergency_contact" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="Social_security_number" type="xs:string" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			</xs:complexType>
			<xs:complexType name="claiminfotype" >
			<xs:sequence>
										<xs:element name="Claim" type="claimType" minOccurs="0" maxOccurs="unbounded"/>
										
			</xs:sequence>
			</xs:complexType>
			<xs:complexType name="claimType">
			<xs:sequence>
										<xs:element name="Medical" type="xs:integer" />
										<xs:element name="Optical" type="xs:integer" />
										<xs:element name="Dental" type="xs:integer" />
			</xs:sequence>
			</xs:complexType>
			<xs:complexType name="insurancetype">
			<xs:sequence>
										<xs:element name="code_insurance" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="subscription_date" type="xs:date" minOccurs="0" maxOccurs="1"/>
										<xs:element name="expiration_date" type="xs:date" minOccurs="0" maxOccurs="1"/>
										<xs:element name="Paid_on_time" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
									
										<xs:element name="Insurance_type" type="xs:string" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			</xs:complexType>
			<xs:complexType name="medicaltype">
			<xs:sequence>
											<xs:element name="last_consultation" type="xs:date" minOccurs="0" maxOccurs="1"/>
											<xs:element name="surgeries" type="xs:boolean" minOccurs="0" maxOccurs="unbounded"/>
											<xs:element name="Labo_test_result" type="xs:string" minOccurs="0" maxOccurs="1"/>
											<xs:element name="Allergies" type="allergieType"/>
											<xs:element name="Currently_under_medication" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
											<xs:element name="Medication_list" type="xs:string" minOccurs="0" maxOccurs="1"/>
											<xs:element name="Addiction" type="xs:string" minOccurs="0" maxOccurs="1"/>
											<xs:element name="Immunization_status" type="xs:string" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			</xs:complexType>
			<xs:complexType name="allergieType" >
			<xs:sequence>
														<xs:element name="Food" type="xs:boolean" minOccurs="0" maxOccurs="unbounded"/>
														<xs:element name="Animal" type="xs:boolean" minOccurs="0" maxOccurs="unbounded"/>
														<xs:element name="Medication" type="xs:boolean" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			</xs:complexType>
			</xs:schema>

=== safaelazrak/XML_project/EMR.xml
<Electronic_Medical_Records xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="EMR.xsd">
	<Employee>
		<personal_data>
			<ID>1</ID>
			<firstname>
				James
			</firstname>
			<lastname>
				Butt
			</lastname>
			<date_of_birth>
				1969-01-22
			</date_of_birth>
			<current_age>52</current_age>
			<weight_in_kg>70</weight_in_kg>
			<Gender>Male</Gender>
			<phone_number>
				504-621-8927
			</phone_number>
			<email_adress>
				jbutt@gmail.com
			</email_adress>
			<city>
				New Orleans
			</city>
			<address>
					6649 N Blue Gum St
				</address>
			<zipcode>
					70116
				</zipcode>
			<emergency_contact>Josephine Butt</emergency_contact>
			<phone_emergency_contact>
				504-845-1427
			</phone_emergency_contact>
			<Social_security_number>9 5 6 7 10 11 8 12 4 2</Social_security_number>
		</personal_data>
		<Claim_informations>
			<Claim>
				<Medical>0</Medical>
				<Optical>56</Optical>
				<Dental>80</Dental>
			</Claim>
			<Claim>
				<Medical>120</Medical>
				<Optical>47</Optical>
				<Dental>867</Dental>
			</Claim>
			<Claim>
				<Medical>0</Medical>
				<Optical>65</Optical>
				<Dental>0</Dental>
			</Claim>
		</Claim_informations>
		<Insurance_informations>
			<code_insurance>JaBu69</code_insurance>
			<subscription_date>2005-06-21</subscription_date>
			<expiration_date>2020-06-21</expiration_date>
			<Paid_on_time>true</Paid_on_time>
			<Insurance_type>Normal</Insurance_type>
		</Insurance_informations>
		<Medical_history>
			<last_consultation>2020-05-21</last_consultation>
			<surgeries>false</surgeries>
			<Labo_test_result>Good</Labo_test_result>
			<Allergies>
				<Food>true</Food>
				<Animal>false</Animal>
				<Medication>false</Medication>
			</Allergies>
			<Currently_under_medication>false</Currently_under_medication>
			<Medication_list>None</Medication_list>
			<Addiction>Smoking</Addiction>
			<Immunization_status>Good</Immunization_status>
		</Medical_history>
	</Employee>
	<Employee>
		<personal_data>
			<ID>2</ID>
			<firstname>
				Josephine
			</firstname>
			<lastname>
				Darakjy
			</lastname>
			<date_of_birth>1970-01-14
			</date_of_birth>
			<current_age>51</current_age>
			<weight_in_kg>66</weight_in_kg>
			<Gender>Female</Gender>
			<phone_number>
				810-292-9388
			</phone_number>
			<email_adress>
				josephine_darakjy@darakjy.org
			</email_adress>
			<city>
				Brighton
			</city>
			<address>
					4 B Blue Ridge Blvd
				</address>
			<zipcode>
					48116
				</zipcode>
			<emergency_contact>Marc Darakjy</emergency_contact>
			<phone_emergency_contact>
				810-374-9840
			</phone_emergency_contact>
			<Social_security_number>12 8 5 1 2 7 10 3 4 9 </Social_security_number>
		</personal_data>
		<Claim_informations>
			<Claim>
				<Medical>0</Medical>
				<Optical>567</Optical>
				<Dental>980</Dental>
			</Claim>
		</Claim_informations>
		<Insurance_informations>
			<code_insurance>JoDa70</code_insurance>
			<subscription_date>2003-08-01</subscription_date>
			<expiration_date>2022-08-01</expiration_date>
			<Paid_on_time>false</Paid_on_time>
			<Insurance_type>Normal</Insurance_type>
		</Insurance_informations>
		<Medical_history>
			<last_consultation>2019-11-18</last_consultation>
			<surgeries>false</surgeries>
			<Labo_test_result>Good</Labo_test_result>
			<Allergies>
				<Food>false</Food>
				<Animal>false</Animal>
				<Medication>true</Medication>
			</Allergies>
			<Currently_under_medication>false</Currently_under_medication>
			<Medication_list>None</Medication_list>
			<Addiction>None</Addiction>
			<Immunization_status>Good</Immunization_status>
		</Medical_history>
	</Employee>
	<Employee>
		<personal_data>
			<ID>3</ID>
			<firstname>
				Art
			</firstname>
			<lastname>
				Venere
			</lastname>
			<date_of_birth>1971-01-22
				
			</date_of_birth>
			<current_age>50</current_age>
			<weight_in_kg>98</weight_in_kg>
			<Gender>Female</Gender>
			<phone_number>
				856-636-8749
			</phone_number>
			<email_adress>
				art@venere.org
			</email_adress>
			<city>
				Bridgeport

			</city>
			<address>
					8 W Cerritos Ave #54
				</address>
			<zipcode>
					8014
				</zipcode>
			<emergency_contact>None</emergency_contact>
			<phone_emergency_contact>	202-555-0166
			</phone_emergency_contact>
			<Social_security_number>6 7 10 11 3 8 2 1 9 4 </Social_security_number>
		</personal_data>
		<Claim_informations>
			<Claim>
				<Medical>230</Medical>
				<Optical>0</Optical>
				<Dental>0</Dental>
			</Claim>
			<Claim>
				<Medical>0</Medical>
				<Optical>100</Optical>
				<Dental>0</Dental>
			</Claim>
			<Claim>
				<Medical>25</Medical>
				<Optical>80</Optical>
				<Dental>0</Dental>
			</Claim>
		</Claim_informations>
		<Insurance_informations>
			<code_insurance>ArVe71</code_insurance>
			<subscription_date>2015-01-09</subscription_date>
			<expiration_date>2024-01-09
</expiration_date>
			<Paid_on_time>true</Paid_on_time>
			<Insurance_type>Premium</Insurance_type>
		</Insurance_informations>
		<Medical_history>
			<last_consultation>2018-09-02</last_consultation>
			<surgeries>true</surgeries>
			<Labo_test_result>Good</Labo_test_result>
			<Allergies>
				<Food>false</Food>
				<Animal>false</Animal>
				<Medication>false</Medication>
			</Allergies>
			<Currently_under_medication>true</Currently_under_medication>
			<Medication_list>Aerus, Nasonex</Medication_list>
			<Addiction>None</Addiction>
			<Immunization_status>Good</Immunization_status>
		</Medical_history>
	</Employee>
		<Employee>
		<personal_data>
			<ID>9</ID>
			<firstname>
				Sage
			</firstname>
			<lastname>
				Wieser
			</lastname>
			<date_of_birth>
				1997-04-23
			</date_of_birth>
			<current_age>24</current_age>
			<weight_in_kg>78</weight_in_kg>
			<Gender>Male</Gender>
			<phone_number>
				617-555-0129
			</phone_number>
			<email_adress>
				sage_wieser@cox.net

			</email_adress>
			<city>
				Sioux Falls
			</city>
			<address>
					5 Boston Ave #88
				</address>
			<zipcode>
					57105
				</zipcode>
			<emergency_contact> Sage Fabien</emergency_contact>
			<phone_emergency_contact>
				617-555-0110
			</phone_emergency_contact>
			<Social_security_number>
				10 9 6 11 1 8 7 2 4 3
			</Social_security_number>
		</personal_data>
		<Claim_informations>
			<Claim>
				<Medical>0</Medical>
				<Optical>0</Optical>
				<Dental>468</Dental>
			</Claim>
			<Claim>
				<Medical>38</Medical>
				<Optical>59</Optical>
				<Dental>0</Dental>
			</Claim>
		</Claim_informations>
		<Insurance_informations>
			<code_insurance>SaWi97</code_insurance>
			<subscription_date>
				2013-07-29
			</subscription_date>
			<expiration_date>2021-07-29
</expiration_date>
			<Paid_on_time>true</Paid_on_time>
			<Insurance_type>Normal</Insurance_type>
		</Insurance_informations>
		<Medical_history>
			<last_consultation>
				2019-01-14
			</last_consultation>
			<surgeries>false</surgeries>
			<Labo_test_result>None</Labo_test_result>
			<Allergies>
				<Food>true</Food>
				<Animal>false</Animal>
				<Medication>false</Medication>
			</Allergies>
			<Currently_under_medication>false</Currently_under_medication>
			<Medication_list>None</Medication_list>
			<Addiction>Smoking</Addiction>
			<Immunization_status>Good</Immunization_status>
		</Medical_history>
	</Employee>
	<Employee>
		<personal_data>
			<ID>10</ID>
			<firstname>
				Kris
			</firstname>
			<lastname>
				Marrier
			</lastname>
			<date_of_birth>
				1993-03-23
			</date_of_birth>
			<current_age>27</current_age>
			<weight_in_kg>65</weight_in_kg>
			<Gender>Male</Gender>
			<phone_number>
				617-555-0116
			</phone_number>
			<email_adress>
				kris@gmail.com
			</email_adress>
			<city>Baltimore</city>
			<address>
					228 Runamuck Pl #2808
				</address>
			<zipcode>
					21224
				</zipcode>
			<emergency_contact>Josephine Marrier</emergency_contact>
			<phone_emergency_contact>
				617-555-0108
			</phone_emergency_contact>
			<Social_security_number>
				1 4 10 2 7 9 11 8 6 5
			</Social_security_number>
		</personal_data>
		<Claim_informations>
			<Claim>
				<Medical>3200</Medical>
				<Optical>0</Optical>
				<Dental>0</Dental>
			</Claim>
		</Claim_informations>
		<Insurance_informations>
			<code_insurance>KrMa93</code_insurance>
			<subscription_date>
				2015-06-04
			</subscription_date>
			<expiration_date>2023-06-04
</expiration_date>
			<Paid_on_time>false</Paid_on_time>
			<Insurance_type>Premium</Insurance_type>
		</Insurance_informations>
		<Medical_history>
			<last_consultation>
				2020-04-12
			</last_consultation>
			<surgeries>false</surgeries>
			<Labo_test_result>Good</Labo_test_result>
			<Allergies>
				<Food>true</Food>
				<Animal>true</Animal>
				<Medication>false</Medication>
			</Allergies>
			<Currently_under_medication>true</Currently_under_medication>
			<Medication_list>false</Medication_list>
			<Addiction>None</Addiction>
			<Immunization_status>Good</Immunization_status>
		</Medical_history>
	</Employee>
	<Employee>
		<personal_data>
			<ID>4</ID>
			<firstname>
				Lenna
			</firstname>
			<lastname>
				Paprocki
			</lastname>
			<date_of_birth>
				1972-01-16
			</date_of_birth>
			<current_age>49</current_age>
			<weight_in_kg>65</weight_in_kg>
			<Gender>Female</Gender>
			<phone_number>
				907-385-4412
			</phone_number>
			<email_adress>
				lpaprocki@hotmail.com
			</email_adress>
			<city>
				Anchorage
			</city>
			<address>
					639 Main St
				</address>
			<zipcode>
					99501
				</zipcode>
			<emergency_contact>Jone Paprocki </emergency_contact>
			<phone_emergency_contact>
				907-921-2010
			</phone_emergency_contact>
